language: minimal

addons:
  ssh_known_hosts: heapy.io

before_install:
  - yarn install
  - nvm install 10
  - export HUGO_VERSION=0.68.3
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb"
  - sudo dpkg -i "hugo_${HUGO_VERSION}_Linux-64bit.deb"

script:
  - hugo --buildFuture

branches:
  only:
    - master

before_deploy:
  - cp public/bjug/index.ics public/bjug/calendar.ics
  - cd public && ln -s ../t t
  - cd public && ln -s ../kotlin_jobs kotlin_jobs
  - cd public && ln -s ../komodo komodo

deploy:
  provider: script
  script: bash .ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master

cache:
  yarn: true
