title: "Heapy - Free and Open-Source Software"
baseURL: "https://heapy.io/"
languageCode: "en-us"
theme: heapy
disqusShortname: "bjug-by"
rssLimit: 10

params:
  description: "Free and Open-Source Software"
  author: "Ruslan Ibragimov"

permalinks:
  events: "events/:slug/"
  fixed: ":title/"

preserveTaxonomyNames: true
