name: "Build"
on:
  push:
  pull_request:
jobs:
  build:
    name: "Hugo build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.122.0"
      - run: hugo --buildFuture
      - run: cp public/bjug/index.ics public/bjug/calendar.ics
      - uses: actions/upload-artifact@v4
        with:
          name: "Frontend Application"
          path: "public/"
          retention-days: 1
  build-and-push-image:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: "Frontend Application"
          path: "public/"
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          tags: ghcr.io/heapy/heapy.io:main
